image: ubuntu:18.04

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt update
    - apt-get install build-essential
    - go build

test:
  stage: test
  script:
    - apt update
    - apt-get install build-essential
    - go test